### ISSUE TITLE
Urgent Issue Post

### ISSUE THREAD

**Issue by mexekanez** [mirumee/django-payments#86] opened 2015-10-16 13:53 UTC
Hi comrads!

In new release 0.7.2 there is an issue from commit by:
Adam (20.07.2015) commit message: Add tests for capture, refund and renew token
In his commit he replaces some logic in 'def process_data' function. It's all ok BUT:
He renames value from:
`payment = self.execute_payment(payer_id)`
to
`execute_payment = self.execute_payment(payment, payer_id)`
and forgets to change it at line 230:
`payment.attrs.payer_info = payment['payer']['payer_info']`

should be:

`payment.attrs.payer_info = execute_payment['payer']['payer_info']`
(I hope that I shouldn't explain why `payment['payer']['payer_info']` wouldn't work)
and all goes well...

p/s I wondering how is your tests gone and you build it :)))

**Comment by mexekanez** [comment] 2015-10-16 13:58
it's all about paypal provider, so in current stage paypal backend doesn't works

**Comment by patrys** [comment] 2015-10-16 14:15
Unfortunately you're correct! We were using `MagicMock` instead of `Mock` in tests and that was the cause the error was not found earlier. Fixed in 0.7.3, thank you for the report. :+1:

**Closed by patrys** 2015-10-16 14:15 UTC
